### ISSUE TITLE
【JavaScript】Magical `this`

### ISSUE THREAD

**Issue by baishusama** [baishusama/baishusama.github.io#1]
### TODO

- [ ] EC stack === call stack ?
- [ ] JS Engine VS JS Compiler
- [ ] What's the scope chain in EC with or without VO ?
